### ISSUE TITLE
fix prices!!!

### ISSUE THREAD

**Issue by damniko** [mirakst/upgraded-potato#18]
hello

my elektricity bill is VERY BIG and i tink it is because of your STUPID ASS PROGRAM

please make cheaper and GOOD DAY to you

**Comment by mirakst** [comment]
Hello,

The mentioned behaviour is by design (see [fuck-our-customers-over.docx](https://m.media-amazon.com/images/I/61zcSevCQ1L._AC_UF1000,1000_QL80_.jpg), section 4.20). Feel free to create a Service Request on the matter, and we will get back to you when it has been estimated.
Thank you.

MIRS

**Comment by damniko** [comment]
\>:(
